#!/usr/bin/python

import sys
import os

argumentList = sys.argv[1:]
output = os.popen("git branch -vv").readlines()
newDict = {}

def check_match():
    newDictSet = set(newDict.values())
    arg = argumentList[0]
    if "*" + arg in newDictSet or " " + arg in newDictSet:
        os.system("git checkout " + arg)
    else:
	print("\nNo match was found")
        checkout()

def checkout():
    listKeys = newDict.keys()
    listKeys.sort()
    print("\n")
    for key in listKeys:
        print(str(key) + ":" + newDict.get(key))
	if key == len(newDict):
	    print("\n")

    userInput = raw_input("Which branch do you want to checkout? ")

    branchToCheckout = newDict.get(int(userInput))
    if branchToCheckout is not None:
        os.system("git checkout " + branchToCheckout)
    else:
	print("This branch does not exist\n")
	checkout()

def create_map():
    for idx, val in enumerate(output):
        splitted = val.split()
        if splitted[0] == "*":
	    newDict.update({ idx + 1:splitted[0] + splitted[1] })
        else:
	    newDict.update({ idx + 1:" " + splitted[0] })

create_map()

if len(argumentList) > 1:
    print("\nThere are way too many arguments. You cannot use more than one argument!!!!")
    checkout()
elif len(argumentList) == 1:
    check_match()
else:
    checkout()
