#!/usr/bin/python

import sys
import os

argumentList = sys.argv[1:]
output = os.popen("git branch -vv").readlines()
newDict = {}

def check_match():
    newDictSet = set(newDict.values())
    arg = argumentList[0] 
    if "*" + arg in newDictSet or " " + arg in newDictSet:
        os.system("git branch -D " + arg)
    else:
	print("There is no branch with that name\n")
	delete()

def delete():
    listKeys = newDict.keys()
    listKeys.sort()
    for key in listKeys:
        print(str(key) + ":" + newDict.get(key))
	if key == len(newDict):
	    print("\n")

    userInput = raw_input("Which branch/branches do you want to delete? ")
    branchesToDelete = userInput.split()

    for val in branchesToDelete:
        branchToDelete = newDict.get(int(val))
        os.system("git branch -D " + branchToDelete[1:])   

def create_map():
    for idx, val in enumerate(output):
        splitted = val.split()
        if splitted[0] == "*":
	    newDict.update({ idx + 1:splitted[0] + splitted[1] })
        else:
	    newDict.update({ idx + 1:" " + splitted[0] })

create_map()

if len(argumentList) > 1:
    print("There are way too arguments. You cannot use more than one argument")
elif len(argumentList) == 1 :
    check_match()
else:
    delete()
